### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by HeinrichHartmann** [HeinrichHartmann/RequestDispatcher#1]
Add timeouts parameter to Request interface. 
Add onTimeout callback to Callback class.
Execute onTimeout method when request times out.

**Comment by renepickhardt** [comment]
shouldn't there also be a way of configuring a standard timeout while creating the dispatcher?

**Comment by HeinrichHartmann** [comment]
Yes, lets realize it as method in the Dispatcher class

setDefaultTimeout(int timeout)

**Comment by HeinrichHartmann** [comment]
Test missing.

**Comment by HeinrichHartmann** [comment]
Done.
