### ISSUE TITLE
need Synchronous execute

### ISSUE THREAD

**Issue by renepickhardt** [HeinrichHartmann/RequestDispatcher#14]
Sometimes we have to have blocking calls and there is no way arround. the API of the dispatcher does not support something like that. the only chance that we have is to do something like that:

```
    final List<Muid> muids = new LinkedList<Muid>();
    dispatcher.execute(new UrlMappingResolveRequest(params.getPathVars(), type), new Callback<MuidResolvedResponse>() {

        @Override
        public void onSuccess(MuidResolvedResponse arg0) {
            muids.add(arg0.getMuid());
        }
    });
    dispatcher.gatherResults(20);
    Muid muid = muids.get(0);
```

it would be much nicer to be able to call:
MuidresolvedResponse resp = dispatcher().executeSynchronous(new UrlMappingResolveRequest(params.getPathVars(), type))

or (as I guess that templated return types might be hard somthing where the response is passed by reference.)

**Comment by HeinrichHartmann** [comment]
Excellent point. Should be not hard to implement.

I will try to make the API more RPC like:

  metalconIdService = New synchronusDispatcher<Req, Rep>(New ZmqAdapter(...))
  Rep = metalconIdService.execute(Req, timeout)

H.

**Comment by HeinrichHartmann** [comment]
Disadvantage of RPC like API is the need to initialize the services another time. Will stick to initial suggestion.
